image: gitlab-registry.cern.ch/pseyfert/texmachine

before_script:
  - echo "deb http://deb.debian.org/debian stable main contrib non-free" >> /etc/apt/sources.list
  - apt-get update
  - apt-get -y upgrade
  - apt-get install -y ttf-mscorefonts-installer

run-tex:
    script:
      - make
    artifacts:
      when: on_success
      expire_in: 2 days
      paths:
        - template.pdf

spellcheck:
    script:
      - touch spelling-mistakes.txt
      - make batch-spellcheck -k -j 1
      - sort -u -o spelling-mistakes.txt spelling-mistakes.txt
    artifacts:
      when: on_failure
      expire_in: 1 week
      paths:
        - spelling-mistakes.txt

# gitlab CI integration for pseyfert/cern-slide-template
# Copyright (C) 2017  Paul Seyfert <pseyfert@cern.ch>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
